version: "3.7"
services:
  nginx:
    image: nginx:1.17-alpine
    container_name: nyt_nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - nyt-app
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        UID: '${UID}'
        GID: '${GID}'
    container_name: nyt_app
    restart: always
    env_file:
      - .env
    volumes:
      - "./src:/var/www/html"
    depends_on:
      - nginx
    networks:
      - nyt-app

networks:
  nyt-app:
    driver: bridge